id: AC0CC044C
title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
type: translation
pechas:
- I9DDBBA44
- I36931D32
- IF69AAF34
- I440D9BAD
- I659E058E
- IB28B2F11
- I13B34113
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - nl
  - pt
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:55.034278
  last_modified_at: 2023-01-04 11:50:55.034291
  collections:
  - Dzongsar Khyentse Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I9DDBBA44/3FC7: A207
  I36931D32/AEC0: A207
  IF69AAF34/729E: A207
  I440D9BAD/F549: A207
  I659E058E/12DB: A207
  IB28B2F11/9A6E: A207
  I13B34113/8FFE: A207
